### ISSUE TITLE
unknown crash when using quickdownload

### ISSUE THREAD

**Issue by adanvdo** [adanvdo/YT-RED-UI#162]
The app crashes when I try to download this reddit video using Quick Download

https://www.reddit.com/r/SipsTea/comments/16uap0j/britney_sears/

```
The system cannot find the file specified

   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeDLSharp.YoutubeDLProcess.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeDLSharp.Helpers.ProcessRunner.<RunThrottled>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeDLSharp.YoutubeDL.<RunVideoDownload>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YTR.Utils.VideoUtil.<DownloadPreferredYtdl>d__28.MoveNext() in E:\Dev\YT-RED\YT-RED\Utils\VideoUtil.cs:line 831
```

I believe it is because of a missing null reference check in the TrayForm, but idk why changing that fixes the problem.

**Comment by adanvdo** [comment]
today this was happening with any type of request, even listing formats
this should be fixed. it's not happening in my dev environment at least
