### ISSUE TITLE
Error loading some Thumbnails

### ISSUE THREAD

**Issue by adanvdo** [adanvdo/YT-RED-UI#177]
the changes in #175 appear to have created an issue with thumbnail selection when listing formats for some links.  This causes an error and stops the formats from being listed.

The remote server returned an error: (404) Not Found.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YTR.Utils.WebUtil.<GetStreamFromUrl>d__0.MoveNext() in E:\Dev\YT-RED\YT-RED\Utils\WebUtil.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YTR.Controls.VideoInfoPanel.<Populate>d__15.MoveNext() in E:\Dev\YT-RED\YT-RED\Controls\VideoInfoPanel.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YTR.MainForm.<getYtdlFormatList>d__61.MoveNext() in E:\Dev\YT-RED\YT-RED\MainForm.cs:line 955

**Comment by adanvdo** [comment]
the app will now sort all available non-webp attachments by preference value, and attempt to get the stream for each one until one is successful, or we have tried them all.
