### ISSUE TITLE
404 Error attempting to load Thumbnail

### ISSUE THREAD

**Issue by adanvdo** [adanvdo/YT-RED-UI#180]
There appear to still be some issues with thumbnail loading.  
Url: https://www.youtube.com/watch?v=gs_fkkAw_3k

```
The remote server returned an error: (404) Not Found.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YTR.Utils.WebUtil.<GetStreamFromUrl>d__0.MoveNext() in E:\Dev\YT-RED\YT-RED\Utils\WebUtil.cs:line 29

Value of 'null' is not valid for 'stream'.

   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at YTR.Controls.VideoInfoPanel.<loadThumbnail>d__16.MoveNext() in E:\Dev\YT-RED\YT-RED\Controls\VideoInfoPanel.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at YTR.Controls.VideoInfoPanel.<Populate>d__15.MoveNext() in E:\Dev\YT-RED\YT-RED\Controls\VideoInfoPanel.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YTR.MainForm.<getYtdlFormatList>d__61.MoveNext() in E:\Dev\YT-RED\YT-RED\MainForm.cs:line 957
```

**Comment by adanvdo** [comment]
this is now fixed
