### ISSUE TITLE
.NET Crash when listing some formats

### ISSUE THREAD

**Issue by adanvdo** [adanvdo/YT-RED-UI#85]
https://www.reddit.com/r/hmm/comments/vtsi35/hmmmm/ example
crashes with the following

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at YT_RED.MainForm.gvFormats_CustomColumnDisplayText(Object sender, CustomColumnDisplayTextEventArgs e) in E:\Dev\YT-RED\YT-RED\MainForm.cs:line 857
   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseCustomColumnDisplayText(CustomColumnDisplayTextEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.RaiseCustomColumnDisplayText(CustomColumnDisplayTextEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseCustomColumnDisplayText(Int32 listSourceIndex, Int32 rowHandle, GridColumn column, Object _value, String displayText, Boolean forGroupRow, CustomColumnDisplayTextEventArgs eventArgs)
   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseCustomColumnDisplayText(Int32 rowHandle, GridColumn column, Object _value, String displayText, Boolean forGroupRow)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.RequestCellDisplayText(GridCellInfo cell)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRegularRowCell(GridViewDrawArgs e, GridCellInfo ci)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRegularRow(GridViewDrawArgs e, GridDataRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRowCoreInternal(GridViewDrawArgs e, GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRowCore(GridViewDrawArgs e, GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRow(GridViewDrawArgs e, GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRows(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawContentsCore(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawCore(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.Draw(ViewDrawArgs ee)
   at DevExpress.XtraGrid.Views.Base.BaseView.Draw(GraphicsCache e)
   at DevExpress.XtraGrid.Views.Grid.GridView.Draw(GraphicsCache e)
   at DevExpress.XtraGrid.GridControl.OnPaintCore(PaintEventArgs e)
   at DevExpress.Utils.Drawing.ControlPaintHelper.PaintWithErrorHandling(PaintEventArgs paintEventArgs, Int32 layer)
   at DevExpress.Utils.Drawing.ControlPaintHelper.ProcessWMPaintCore(Boolean beginPaint, IntPtr hdc, Rectangle rectangle, Rectangle[] clipBounds)
   at DevExpress.Utils.Drawing.ControlPaintHelper.ProcessWMPaint(Message& m)
   at DevExpress.XtraGrid.GridControl.CheckProcessMsg(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
YT-RED
    Assembly Version: 1.0.1.5
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/YT-RED/YT-RED.exe
----------------------------------------
DevExpress.XtraBars.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.XtraBars.v22.1.DLL
----------------------------------------
DevExpress.Utils.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.Utils.v22.1.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Data.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.Data.v22.1.DLL
----------------------------------------
Xabe.FFmpeg
    Assembly Version: 5.2.0.0
    Win32 Version: 5.2.0.0
    CodeBase: file:///E:/YT-RED/Xabe.FFmpeg.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.XtraEditors.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.XtraEditors.v22.1.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
DevExpress.Data.Desktop.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.Data.Desktop.v22.1.DLL
----------------------------------------
DevExpress.Drawing.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.Drawing.v22.1.DLL
----------------------------------------
DevExpress.BonusSkins.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.BonusSkins.v22.1.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
DevExpress.XtraGrid.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.XtraGrid.v22.1.DLL
----------------------------------------
DevExpress.Printing.v22.1.Core
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.Printing.v22.1.Core.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
DevExpress.XtraLayout.v22.1
    Assembly Version: 22.1.3.0
    Win32 Version: 22.1.3.0
    CodeBase: file:///E:/YT-RED/DevExpress.XtraLayout.v22.1.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
YoutubeDLSharp
    Assembly Version: 0.4.2.2271
    Win32 Version: 0.4.2.2271
    CodeBase: file:///E:/YT-RED/YoutubeDLSharp.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///E:/YT-RED/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by adanvdo** [comment]
this was being caused by the filesize column trying to parse the decimal string of a format's file size or bitrate when the value was 0.

I have added handling for this and it appears to be fixed
