### ISSUE TITLE
Error downloading reddit video

### ISSUE THREAD

**Issue by adanvdo** [adanvdo/YT-RED-UI#97]
I am getting the following error when trying to download a reddit video

7/28/2022 10:27:22 AM ----------------------------

Sequence contains no matching element

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at YT_RED.Utils.VideoUtil.<PrepareStreamConversion>d__12.MoveNext() in E:\Dev\YT-RED\YT-RED\Utils\VideoUtil.cs:line 357

**Comment by adanvdo** [comment]
`parameters` was missing a check to handle it being null or containing no parameter values. 
this has been fixed.

**Comment by adanvdo** [comment]
This is still happening when attempting to download a specific format

**Comment by adanvdo** [comment]
This was cause by accidentally using `.First()` instead of `.FirstOrDefault()`
I've corrected any other instances of this as well
